"""add analysis_reports table

Revision ID: 51a2975f1c79
Revises: de599ab11858
Create Date: 2026-03-19 20:51:44.449499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51a2975f1c79'
down_revision: Union[str, Sequence[str], None] = 'de599ab11858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_summary', sa.Text(), nullable=False),
    sa.Column('conviction_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_as_of', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_created_at'), 'analysis_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_reports_report_type'), 'analysis_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_analysis_reports_symbol'), 'analysis_reports', ['symbol'], unique=False)
    op.create_index('ix_analysis_reports_symbol_created_at', 'analysis_reports', ['symbol', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_analysis_reports_type_created_at', 'analysis_reports', ['report_type', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_reports_type_created_at', table_name='analysis_reports')
    op.drop_index('ix_analysis_reports_symbol_created_at', table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_symbol'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_report_type'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_created_at'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    # ### end Alembic commands ###
